# Generated by Django 4.0.3 on 2024-07-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_rename_content_question_content2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='content2',
            new_name='content',
        ),
    ]
